### PR TITLE
Pathfinding fixes and improvements

### PR DESCRIPTION
**Pull request by CrashDome**
Oh boy.... I think I went down a big rabbit hole with this one.

I wanted to improve pathfinding a few months ago. So I went looking through what is currently there, some stale branches, and general fooling around from other people I found from years ago. I attempted to make something useful and neat. What I ended up with was three complete rewrites, less hair on my head, and a few discoveries. 

I can't even attempt to explain everything so I'm going to do two things: Give a summary of what it can and cannot do and then throw up a quick video.

Biggest discovery was about a month ago. During perf testing I found that BI's hashmap is so much faster than CBAs that without it, this would be a slow mess. 

Here's quick list of what it CAN do:

- Dual layer pathfinding - large for rough checking and small for better resolution along the way
- Single large layer pathfinding for doing "can I get there" checks if needed by other modules
- Follows a more natural path akin to native AI
-- Depending on procedure, you might find useful ways to create custom objectives where paths naturally funnel such as bridges or roads
- Cross over small or large bridges (even the ones on Tanoa)
- Water grid square compression to save memory
- Can allow units to traverse rivers or shallow water or 'swim' if capable
- Custom pathfinding by faction to have units take paths appropriate to their doctrine
- Get a unit 'close' to waypoint if waypoint is unreachable
- Keep large vehicles out of dense areas (eg trees and buildings) and pathfind around them 
- Height based pathfinding (stay high or low) - still WIP
- Shorten long paths which might consist of 100+ waypoints but try not to cut too many corners
- Bail out of pathfinding if stuck but remember last closest point and end there
- Do all this extremely fast even on 50m x 50m grid squares.
- Do intense water checks grid by grid as it's pathfinding along a coast, river, or swampy area.
- Replaces all SeaCrossing checks by OPCOM if pathfinding enabled so units CAN use bridges and OPCOM will send them if able - again even on Tanoa
- Is compatible with Sea Travel option in the sense it negates it. Since units are currently limited to 100m swimming and wont use boats if less than 200m [WIP] - as I'd like to see the option for people to use Sea Travel for infantry at some point this will change. Just dont know exactly how to approach it yet
- Make Coffee or Tea - (j/k)

Here's what it CANT do (yet):

- Tell the OPCOM/TACOM that a unit in a section can only get close and not actually reach the destination. 
- NOT Drive through an objective (e.g recon) that has a road through it (because TACOM said go to other side but there is a river in the way)  >:(
- Replace spawned AI pathfinding - although the waypoints do help, AI road driving while spawned is still a toss up
- Make Coffee or Tea

I would really appreciate feedback and testing if possible. I know this touches a lot of modules so, I want to be sure nothing is broken. I have been testing in a large mission and haven't seen anything bad really. There might be an occasional gap where units should not go (and boy will it find them). Overall, though, it makes for very interesting battles. I'm interested in performance and any errors. I'd really like to get this in soon. 

Here is a quick quide to the pathfinding procedures that can be customized (maybe wiki-fy it?):
[ALiVE Pathfinding Guide.pdf](https://github.com/ALiVEOS/ALiVE.OS/files/9637957/ALiVE.Pathfinding.Guide.pdf)

Short and Quick video I just made showing a few in action path findings so you can see without pulling code down: 
[VIDEO](https://www.youtube.com/watch?v=Rd2bwHb0zBc)
Note: I did cut things together but there is no speed ups of video. Units are running 200% speed on a 5600x, 16gb RAM, w/ 2070 super gfx card. All pathfinding you see with the debug markers is real time.

TODO:

- [ ] Clean up redundant code
- [ ] Add a few external functions that might be useful
- [ ] Figure out a better height weight calc
- [ ] better Sea Travel compatibility

Thanks

### CODE REVIEW

**Comment by DarrellJMartin** [comment]
Merged for public testing

**Comment by Azraeel** [comment]
Line 160 in fnc_pathfindingGrid.sqf 
returns undefined variable for _result
pretty spammy too

**Comment by CrashDome** [comment]
I suspect it's from trying to get neighbors from around the edges of the map. More likely to happen in layer 1 checks, hence line 160 and not 168. I'll double check that theory and just throw an isnil check in both if that is truly the case. If not, I have more digging to do.

**Comment by CrashDome** [comment]
> should come join the alive discord, you are a mystery rn :)

Can't find it! :)  DM me an invite and I'll pop in.

**Pull request merged**
