### PR TITLE
[FIX] 1275 lines with "Item STR_ZEC_??? listed twice"

### PR DESCRIPTION
**Pull request by shukari**
RPT log:
```
12:30:41 Item STR_ZEC_Civilian listed twice
12:30:41 Item STR_ZEC_CivilianDesert listed twice
12:30:41 Item STR_ZEC_CivilianWoodland listed twice
12:30:41 Item STR_ZEC_CivilianPacific listed twice
12:30:41 Item STR_ZEC_Guerrilla listed twice
12:30:41 Item STR_ZEC_GuerrillaDesert listed twice
12:30:41 Item STR_ZEC_GuerrillaWoodland listed twice
12:30:41 Item STR_ZEC_GuerrillaPacific listed twice
12:30:41 Item STR_ZEC_Military listed twice
```

Because "/addons/composition_a3/stringtable.xml" and "/optional/composition_apex/stringtable.xml" a duplicates.

### CODE REVIEW

**Comment by marceldev89** [comment]
Might just as well delete the entire file. :smiley:

**Comment by marceldev89** [comment]
On a second thought, the strings should be where the compositions are defined. We will do this in an automated way. Thank you for giving a hears up though. :)

**Comment by marceldev89** [comment]
Here's the new PR if you're interested: https://github.com/ALiVEOS/ALiVE.OS/pull/337 :smile:

**Comment by shukari** [comment]
n1, thanks

**Pull request closed without merging**
