### PR TITLE
Improve Core Parts of Fnc_createRoadBlock

### PR DESCRIPTION
**Pull request by Azraeel**
This improves some parts of Fnc_createRoadBlock, hopefully.

### CODE REVIEW

**Comment by DavisBrown723** [comment]
Is this undergoing changes?

**Comment by Azraeel** [comment]
> Is this undergoing changes?

dont think so, i just decided to keep it for a bit since looked like everyone was busy and thats fine :)

**Comment by DavisBrown723** [comment]
Things don't move very fast around here anymore

**Comment by Azraeel** [comment]
> Things don't move very fast around here anymore

thats fine! im patient.

**Comment by Azraeel** [comment]
Ill get around to this sometime in the future

**Pull request closed without merging**
