### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by DavisBrown723**
It's time to stop living in the past. The world has embraced new technology and it is time we do the same.

### CODE REVIEW

**Review by MeltedPixel — CHANGES_REQUESTED** [review]
What have you done.

**Comment by svencc** [comment]
I don´t think that this should be considered as serious improvement.

**Comment by friznit** [comment]
You spelt modernise wrong

**Comment by DavisBrown723** [comment]
I spelled it the modern way

**Pull request closed without merging**
