### PR TITLE
[X_LIB] ALiVE_fnc_isHC cleanup

### PR DESCRIPTION
**Pull request by Whigital**
Removes the following ALiVE_fnc_isHC references:

* call in 'preinit.sqf'
* entry in 'functions\function_list.txt'
* function definition in 'config\CfgFunctions.hpp'
* the script 'functions\misc\fnc_isHC.sqf' itself

### CODE REVIEW

**Comment by Whigital** [comment]
My bad, just did a search for the `isHC` variable the function sets and it pops up all over the place. I initially only checked where the function was called and focused only on the `headlessClients` var used by the AI_Distributor.

Commiting this WILL break a lot of other modules.

**Comment by Whigital** [comment]
From what i can see, there are no calls to the function that expects a return, and with the "old" *headlessClients* taken away, returning `isHC` after assigning it seems redundant:

Before:
```sqf
isHC = !isDedicated && {!hasInterface};

if (isNil "headlessClients" && isServer) then {
    headlessClients = [];
    publicVariable "headlessClients";
};

if (isHC) then {
    [] spawn {
        waituntil {!isnil "headlessClients" && {!isNull player}};

        headlessClients pushback player;
        publicVariable "headlessClients";
    };
};

isHC;
```

After:
```sqf
isHC = !isDedicated && {!hasInterface};

isHC;
```

**Comment by highhead** [comment]
if i get that right, the headlessClient array isn't set anymore when doing that:

isHC = !isDedicated && {!hasInterface};

isHC;

is the array set somewhere else?

**Comment by Whigital** [comment]
@highhead `headlessClients` array **was** used in `ALiVE_fnc_aiDistributor` before it was rewritten, and as far as i can find, the array isn't used or set anywhere else.

The `isHC` var on the other hand is used in multiple places.

**Comment by highhead** [comment]
someone merge it please, im always breaking it!

**Comment by DavisBrown723** [comment]
Holding my breath

**Pull request merged**
