### PR TITLE
Updating Country Letrim, Northern Ireland Index

### PR DESCRIPTION
**Pull request by diveyez**
Updating Country Letrim, Northern Ireland Index

May need obj categorizations, removed them for now due to map being beta, and also having had large changes.

### CODE REVIEW

**Comment by diveyez** [comment]
May need obj categorizations, removed them for now due to map being beta, and also having had large changes.

**Comment by marceldev89** [comment]
What exactly did you remove?

**Comment by diveyez** [comment]
This Map was updated, and some object placements were changed and moved around. Just catching up with its development.

**Comment by diveyez** [comment]
**If** you dont pull this, _ill be updating the branch in a few days_, 
if you want to wait until **further review** that is fine.

**Comment by marceldev89** [comment]
I guess I'll wait until the update. ^^

Op vr 18 okt. 2019 23:04 schreef diveyez <notifications@github.com>:

**Comment by diveyez** [comment]
Update, the changes are plainly visible and really do not need explanations, OPX has one Mil Cluster, and the other, has one, or two. Cannot recall. Good run. Ill close this branch and start a new one once you merge. Thanks!

**Comment by marceldev89** [comment]
What are the proper names for the other 2 maps you've added?

**Comment by diveyez** [comment]
Ah, I already removed them, give me a few to get that information.
Suursaari https://steamcommunity.com/sharedfiles/filedetails/?id=1680294609
MOUT Town https://steamcommunity.com/sharedfiles/filedetails/?id=1834987833

**Comment by diveyez** [comment]
Thank You Marcel, I can always count on you to be ready with speed to get work done it seems!

I made a discord for development of all kinds, feel free to join https://discord.gg/cwcV6Hd

Hope to see you there to have some social time with like minded creative people!

**Comment by marceldev89** [comment]
I'm not that active on discord or any other social platforms to be honest. If you need to you can reach me on the ALiVE or ArmA discord I guess. :smiley:

**Comment by diveyez** [comment]
I cannot get into the Arma discord and this is strange because I have never been to discord.gg/arma3

**Comment by DavisBrown723** [comment]
https://discord.gg/JWACmb

**Pull request merged**
