### PR TITLE
Mapindexing updates

### PR DESCRIPTION
**Pull request by diveyez**
+Uzbin Valley Afghanistan Map Index
[Workshop Page](
https://steamcommunity.com/sharedfiles/filedetails/?id=1882424760)

### CODE REVIEW

**Comment by marceldev89** [comment]
Hmm something is weird about this PR. It seems to like it wants to reapply the previous map updates already merged. Kinda afraid to click the merge button. :sweat_smile: 

Can you check whether you're able to fix that?

**Comment by diveyez** [comment]
Please elaborate what PR means!

**Comment by GunnyDev** [comment]
PR = Pull Request

**Comment by diveyez** [comment]
Thanks.
Yeah, It was not supposed to do that.
If you already merged a previous version, ignore this and I will be posting an overhaul in the coming weeks.

**Pull request closed without merging**
