### PR TITLE
Added new macros 'PATHTO_FUNC and 'FUNC_FILEPATH'

### PR DESCRIPTION
**Pull request by dixon13**
**When merged this pull request will:**

- add the new `PATHTO_FUNC` macro, `PATHTO_FUNC` accepts one argument `<function name>`
- add the new `FUNC_FILEPATH` macro, `FUNC_FILEPATH` accepts two arguments
    `<function name>` and `<description (string)>`

All modules are taking advantage of the new macros except `x_lib`.
There were a few cases where the `PATHTO_FUNC` and `FUNC_FILEPATH` cannot be utilized due to the file being placed in a sub-folder of a component
The macro will put in place a standard as to where function files should normally be and will make it easier for people to generate a CfgFunctions file with these macros since they won't have to type out the entire path to their file every time they create a new function or type out another class.

**What the macros looks like in script_mod.hpp**
`#define PATHTO_FUNC(var1) QUOTE(PATHTO_SYS(PREFIX,COMPONENT,DOUBLES(fnc,var1)))`
```c#
#define FUNC_FILEPATH(func,desc) class func {\
  description = desc;\
  file = QUOTE(PATHTO(DOUBLES(fnc,func)));\
  recompile = RECOMPILE;\
}
```

**How to use:**

1. Place you're function file in the root of a component, i.e.
    `\x\alive\addons\main\fnc_myFunction.sqf` or `\x\alive\addons\main\fnc_myFunction2.sqf`
2. The class CfgFunctions will need to be defined like so...
```c#
class CfgFunctions {
  class PREFIX {
    class COMPONENT {
      class myFunction {
        description = "My Function";
        file = PATHTO_FUNC(myFunction);
        recompile = RECOMPILE;
      };
      FUNC_FILEPATH(myFunction2,"Description");
    };
  };
};
```
And as you can see above I used **`PATHTO_FUNC`**. It only takes one argument and that's the name of you're function.
Now it's ready for use and it can be called like so, `[] call ALiVE_fnc_myFunction;`

**`FUNC_FILEPATH`** replaces an entire class entry makes it easier for users to add new functions into the config with less tediousness.

### CODE REVIEW

**Comment by marceldev89** [comment]
Can you convert the tabs to (4) spaces? It's not "officially" mentioned anywhere but it's the preferred indentation method.

**Comment by dixon13** [comment]
I will @marceldev89

**Comment by dixon13** [comment]
I just realized my python script is adding indentations incorrectly

**Comment by dixon13** [comment]
Don't merge yet will fix the spacing

**Comment by dixon13** [comment]
Probably won't be able to get this fixed until later today or sometime this weekend

**Comment by dixon13** [comment]
Spacing fixed and ready for merge @SpyderBlack723

**Comment by dixon13** [comment]
Are you guys ok with `FUNC_FILEPATH` all of a sudden I feel like it's not a good name or it's too long? Any thoughts on this?

**Comment by tupolov** [comment]
@dixon13 love the fact that you have taken a look at this and put the effort in to come up with the macro, however, at this point we probably are not going to deviate from CBA standards for macro implementation. We use them where they are useful, but don't want to implement our own. 

Hope you understand and that you continue to contribute to ALiVE.

**Comment by dixon13** [comment]
I will implement into CBA then

**Pull request closed without merging**
