### PR TITLE
Optional commanders tablet model for ALiVE

### PR DESCRIPTION
**Pull request by Asmodeuz**
Optional commanders tablet model for more "traditional warfare"
scenarios.

ALiVE_mapbag by Asmodeus derived from the original ALiVE_tablet template
by SpyderBlack723.
Frame of the mapbag model photographed by Anssi.

Update 02172017 - changes to the layout so that the edges shouldn't cover the interface anymore (see: https://github.com/ALiVEOS/ALiVE.OS/issues/279#issuecomment-279857981)

### CODE REVIEW

**Comment by SpyderBlack723** [comment]
@Asmodeuz Can you do me a favor and resize this to 4096 x 4096 ie. power of 2

Arma isn't wanting to display the updated image: https://gyazo.com/79d8d0f54184d680bd3452603d8a915e

I tried resizing myself via some online psd editors but couldn't quite maintain the size of the tablet image itself... : https://gyazo.com/3ba15157a3d6876f23ca09b473e9eef2

**Comment by SpyderBlack723** [comment]
https://gyazo.com/a7de1d9f48e3d65f2cd80c7aeb134521

Its yuuge now. Slightly overflows the top of the screen but can't really do anything about that.

**Comment by Asmodeuz** [comment]
I'd say that looks decent at least.
Though it's easy to see some complaints coming in because the frame blocks some of the vanilla UI there on the top right corner. What do you think?

The top "flap" could be opened like this: http://i1370.photobucket.com/albums/ag278/testusah123/topflap_zpstllhsgxw.jpg~original

I have a couple of images with the flap folded to the backside but decided to use the one with the flap closed because back then (last December) I thought that did look better out of the two versions.

Should we deem necessary to change the version I would really need to ask the friend of mine to take new pictures with the flap opened and folded to the backside since the ones I have now aren't (imho) of enough high quality.

**Comment by SpyderBlack723** [comment]
Up to you really on whether the image should be swapped, I can always make the screen size of the current module larger to fit more UI elements.

**Comment by SpyderBlack723** [comment]
Oh, I see what you mean about UI blocking. I don't really think that matters, that information isn't relevant to tablet, so it shouldn't need to be immediately known.

**Comment by Asmodeuz** [comment]
I'd say leave it like that (until a public outcry forces me or someone else to _"fix that god damn model so it won't overflow the top of the screen !!#=¤#?"_

I did a side by side comparison with the one that can already be seen in the game and with the image I shared where the top flap is moved to the backside and I still coulndn't see how the latter version would be any better (even if it wouldn't overflow the top screen anymore).

**Comment by SpyderBlack723** [comment]
Merged to accompany b179f7c6e05e3c8978ae233b4b5d0b1919f3c530

**Pull request merged**
